name: Build RustPotato

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch: # Позволяет запускать сборку вручную кнопкой в интерфейсе GitHub

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        target: x86_64-pc-windows-msvc

    - name: Build Release
      run: cargo build --release

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: RustPotato-Binary
        path: target/release/*.exe
